version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


  django:
    restart: always
    build:
      context: .
    env_file:
      - .env
    container_name: django
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - my_static_files:/app/venv/lib/python3.11/site-packages/django/contrib/admin/static/admin/
      - my_media_files:/app/admin_panel/media/
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/app
    command: sh -c "cd ./admin_panel && gunicorn --bind 0.0.0.0:8080 admin_panel.wsgi:application"

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - my_static_files:/static/admin/
      - my_media_files:/media/
    depends_on:
      - django

volumes:
  pg_data:
  my_static_files:
  my_media_files: