version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


  django:
    build:
      context: .
    env_file:
      - .env
    container_name: django
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/app
    command: sh -c "cd ./admin_panel && gunicorn --bind 0.0.0.0:8080 admin_panel.wsgi:application"


volumes:
  pg_data: