# Generated by Django 5.0 on 2023-12-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('insta_link', models.CharField()),
                ('image_data', models.BinaryField()),
            ],
        ),
    ]
