# Generated by Django 5.0 on 2024-01-16 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
                ('goal_uk', models.CharField()),
                ('goal_en', models.CharField()),
                ('donata_link', models.CharField()),
                ('quick_donate', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Терміновий збір',
            },
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Merch',
            },
        ),
        migrations.CreateModel(
            name='OurActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Наша діяльність',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Звіти',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uk', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='images/support_logo')),
            ],
            options={
                'verbose_name_plural': 'Нас підтримують',
            },
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uk', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('role_uk', models.CharField(max_length=255)),
                ('role_en', models.CharField(max_length=255)),
                ('insta_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image_data', models.ImageField(upload_to='images/teammate_avatar')),
            ],
            options={
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='ReportsImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/photos')),
                ('title_uk', models.CharField()),
                ('title_en', models.CharField()),
                ('quantity', models.IntegerField()),
                ('image_reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.reports')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/photos')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.ouractivity')),
                ('donate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.donate')),
                ('merch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.merch')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.section')),
            ],
        ),
        migrations.CreateModel(
            name='TextActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
                ('text_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='drf.ouractivity')),
            ],
        ),
    ]
