# Generated by Django 5.0 on 2023-12-28 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uk', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('role_uk', models.CharField(max_length=255)),
                ('role_en', models.CharField(max_length=255)),
                ('insta_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image_data', models.ImageField(upload_to='images/teammate_avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/photos')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.section')),
            ],
        ),
    ]
