# Generated by Django 5.0 on 2023-12-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image_data',
            field=models.ImageField(upload_to=''),
        ),
    ]
