# Generated by Django 5.0 on 2024-01-17 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickDonate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donate_link', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Швидкий донат',
            },
        ),
        migrations.RemoveField(
            model_name='donate',
            name='quick_donate',
        ),
    ]
