# Generated by Django 5.0 on 2023-12-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'REBEL VOLUNTEERS'},
        ),
        migrations.AlterModelOptions(
            name='teammate',
            options={'verbose_name_plural': 'Команда'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
    ]
