# Generated by Django 5.0 on 2023-12-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_alter_team_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image_data',
            field=models.ImageField(upload_to='team_images/'),
        ),
    ]
