# Generated by Django 5.0 on 2023-12-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0003_ouractivity_alter_section_options_photo_our_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='our_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.ouractivity'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.section'),
        ),
    ]
