# Generated by Django 5.0 on 2023-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0004_alter_team_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('role', models.CharField()),
                ('insta_link', models.CharField()),
                ('image_data', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
