# Generated by Django 5.0 on 2023-12-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0005_teammate_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='image_data',
            field=models.ImageField(upload_to='images/teammate_avatar'),
        ),
    ]
