# Generated by Django 5.0 on 2023-12-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0006_alter_teammate_image_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammate',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='teammate',
            old_name='role',
            new_name='name_uk',
        ),
        migrations.AddField(
            model_name='teammate',
            name='role_en',
            field=models.CharField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammate',
            name='role_uk',
            field=models.CharField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammate',
            name='insta_link',
            field=models.CharField(null=True),
        ),
    ]
