# Generated by Django 5.0 on 2023-12-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0007_rename_name_teammate_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammate',
            old_name='name_uk',
            new_name='name_ukе',
        ),
    ]
