# Generated by Django 5.0 on 2023-12-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0008_rename_name_uk_teammate_name_ukе'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammate',
            old_name='name_ukе',
            new_name='name_uk',
        ),
    ]
