# Generated by Django 5.0 on 2023-12-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0009_rename_name_ukе_teammate_name_uk'),
    ]

    operations = [
    ]
