# Generated by Django 5.0 on 2024-01-02 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0009_alter_photo_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouractivity',
            name='text_1_en',
        ),
        migrations.RemoveField(
            model_name='ouractivity',
            name='text_1_uk',
        ),
        migrations.RemoveField(
            model_name='ouractivity',
            name='text_2_en',
        ),
        migrations.RemoveField(
            model_name='ouractivity',
            name='text_2_uk',
        ),
        migrations.RemoveField(
            model_name='ouractivity',
            name='text_3_en',
        ),
        migrations.RemoveField(
            model_name='ouractivity',
            name='text_3_uk',
        ),
        migrations.CreateModel(
            name='TextActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
                ('text_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='drf.ouractivity')),
            ],
        ),
    ]
