# Generated by Django 5.0 on 2024-01-02 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0010_remove_ouractivity_text_1_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
                ('goal_uk', models.CharField()),
                ('goal_en', models.CharField()),
                ('donata_link', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Терміновий збір',
            },
        ),
        migrations.AlterModelOptions(
            name='ouractivity',
            options={'verbose_name_plural': 'Наша діяльність'},
        ),
        migrations.AddField(
            model_name='photo',
            name='donate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.donate'),
        ),
    ]
