# Generated by Django 5.0 on 2024-01-05 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0011_donate_alter_ouractivity_options_photo_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Звіти',
            },
        ),
        migrations.CreateModel(
            name='ReportsImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/photos')),
                ('title_uk', models.CharField()),
                ('title_en', models.CharField()),
                ('quantity', models.IntegerField()),
                ('image_reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='drf.reports')),
            ],
        ),
    ]
