# Generated by Django 5.0 on 2023-12-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0011_alter_teammate_insta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='insta_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
