# Generated by Django 5.0 on 2024-01-06 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0013_alter_reportsimage_image_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Merch',
            },
        ),
        migrations.AlterField(
            model_name='reportsimage',
            name='image_reports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.reports'),
        ),
        migrations.AddField(
            model_name='photo',
            name='merch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='drf.merch'),
        ),
    ]
