# Generated by Django 5.0 on 2024-01-06 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0014_merch_alter_reportsimage_image_reports_photo_merch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uk', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='images/support_logo')),
            ],
            options={
                'verbose_name_plural': 'Нас підтримують',
            },
        ),
    ]
