# Generated by Django 5.0 on 2024-01-09 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_uk', models.CharField()),
                ('title_en', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_uk', models.CharField()),
                ('title_en', models.CharField()),
                ('quantity', models.IntegerField()),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='report.reports')),
            ],
        ),
    ]
