# Generated by Django 5.0 on 2024-01-09 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsPV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Фото відео звіт',
            },
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name_plural': 'Загальний результат'},
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/photos')),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='report.reportspv')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.CharField()),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='report.reportspv')),
            ],
        ),
    ]
