# Generated by Django 5.0 on 2024-01-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chevronphoto',
            options={'verbose_name_plural': 'Військові друзі'},
        ),
    ]
