# Generated by Django 5.0 on 2024-01-10 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportspv_alter_reports_options_photo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_uk', models.CharField()),
                ('title_en', models.CharField()),
                ('text_uk', models.TextField()),
                ('text_en', models.TextField()),
                ('news_url', models.CharField()),
                ('image', models.ImageField(upload_to='images/photos')),
            ],
            options={
                'verbose_name_plural': 'Про нас говорять',
            },
        ),
    ]
