# Generated by Django 5.0 on 2024-01-10 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_thanksphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChevronPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/photos')),
            ],
            options={
                'verbose_name_plural': 'Шеврони',
            },
        ),
        migrations.AlterModelOptions(
            name='thanksphoto',
            options={'verbose_name_plural': 'Подяки'},
        ),
    ]
